### ISSUE TITLE
更新BlockTalk PPT

### ISSUE THREAD

**Issue by kiraluo163** [kiraluo163/BlockTalk#3]
- 提升一下排版和设计
- 增强一下“团队介绍“的背景实力
- 丰富一下“成功案例”部分

**Comment by kiraluo163** [comment]
In Progress

**Comment by Ginnnny** [comment]
完成了整体的排版和设计；
和大大一起补充完成了团队介绍；
对初版的desk完善结束；
等以后有新的内容再重新修缮。
